#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}▸${NC} $1"; }
warn()  { echo -e "${YELLOW}▸${NC} $1"; }
fail()  { echo -e "${RED}✗${NC} $1"; exit 1; }

echo ""
echo "  ┌──────────────────────────────────────┐"
echo "  │     Gradient — Local Dev Setup       │"
echo "  └──────────────────────────────────────┘"
echo ""

# ── 1. Check prerequisites ───────────────────────────────────────────
info "Checking prerequisites..."

command -v go >/dev/null 2>&1    || fail "Go is not installed. Install Go 1.21+ from https://go.dev/dl/"
command -v docker >/dev/null 2>&1 || fail "Docker is not installed. Install Docker from https://docker.com"

GO_VERSION=$(go version | grep -oE 'go[0-9]+\.[0-9]+' | head -1)
info "  Go: $GO_VERSION ✓"
info "  Docker: $(docker --version | head -c 40) ✓"

# ── 2. Create .env if missing ────────────────────────────────────────
if [ ! -f .env ]; then
  info "Creating .env for local development..."
  if [ -f .env.example ]; then
    cp .env.example .env
    # Override production defaults with dev-friendly values
    sed -i.bak \
      -e 's|^ENV=.*|ENV=development|' \
      -e 's|^DATABASE_URL=.*|DATABASE_URL=postgres://gradient:gradient@localhost:5432/gradient?sslmode=disable|' \
      -e 's|^API_URL=.*|API_URL=http://localhost:6767|' \
      -e 's|^NATS_URL=.*|NATS_URL=nats://localhost:4222|' \
      -e 's|^LOG_LEVEL=.*|LOG_LEVEL=debug|' \
      -e 's|^WARM_POOL_DEFAULT_SIZE=.*|WARM_POOL_DEFAULT_SIZE=0|' \
      -e 's|^WARM_POOL_MAX_SIZE=.*|WARM_POOL_MAX_SIZE=0|' \
      .env && rm -f .env.bak
    info "  Copied .env.example → .env (with dev overrides)"
  else
    cat > .env <<'EOF'
# ─── Gradient Local Dev Config ───
# Auto-generated by make dev. For production, use .env.example as a base.
PORT=6767
ENV=development
DATABASE_URL=postgres://gradient:gradient@localhost:5432/gradient?sslmode=disable
API_URL=http://localhost:6767

# Auth — dev mode: no JWT verification when these are empty
CLERK_SECRET_KEY=
CLERK_PUBLISHABLE_KEY=
CLERK_JWKS_URL=
CLERK_PEM_PUBLIC_KEY=

# JWT signing — auto-generated by make dev if empty
JWT_SECRET=

# Stripe — REQUIRED even in dev (use test keys: sk_test_...)
# Billing goes through Stripe for all tiers. Without this, env creation is blocked.
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
STRIPE_PRICE_CREDITS_ID=
STRIPE_CREDIT_METER_EVENT_NAME=gradient_credits
STRIPE_CREDIT_METER_CUSTOMER_KEY=stripe_customer_id
STRIPE_CREDIT_METER_VALUE_KEY=credits
FREE_TRIAL_CREDIT_USD=10

# Hetzner — environments won't provision, but API + CLI + tests work
HETZNER_API_TOKEN=
HETZNER_LOCATION=fsn1
HETZNER_SSH_KEY_IDS=
HETZNER_SSH_PRIVATE_KEY=
HETZNER_FIREWALL_ID=
HETZNER_NETWORK_ID=
HETZNER_IMAGE_ID=

# Registry — snapshots won't push, but snapshot metadata still recorded
REGISTRY_URL=
REGISTRY_USER=
REGISTRY_PASS=

# Vault — secret syncs record metadata only
VAULT_ADDR=
VAULT_TOKEN=

# Agent — not installed on servers in dev (no AGENT_DOWNLOAD_URL)
AGENT_DOWNLOAD_URL=

# NATS — started by `make dev` via docker compose
NATS_URL=nats://localhost:4222
NATS_AUTH_TOKEN=
NATS_MAX_AGE=168h

# Warm Pool — disabled in dev (0 = all boots are cold, no cost)
WARM_POOL_DEFAULT_SIZE=0
WARM_POOL_MAX_SIZE=0
WARM_POOL_IDLE_TIMEOUT=10m

# GitHub App — webhooks work but won't verify HMAC without these
GITHUB_APP_ID=
GITHUB_APP_WEBHOOK_SECRET=

# MCP Server
MCP_SERVER_PORT=8081

# Logging
LOG_LEVEL=debug
EOF
  fi
  info ".env created ✓"
else
  info ".env already exists ✓"
fi

# Ensure the credits-based Stripe billing vars exist on older local .env files.
if ! grep -q "^STRIPE_PRICE_CREDITS_ID=" .env 2>/dev/null; then
  cat >> .env <<'EOF'
STRIPE_PRICE_CREDITS_ID=
STRIPE_CREDIT_METER_EVENT_NAME=gradient_credits
STRIPE_CREDIT_METER_CUSTOMER_KEY=stripe_customer_id
STRIPE_CREDIT_METER_VALUE_KEY=credits
FREE_TRIAL_CREDIT_USD=10
EOF
  info "Added credits billing env vars to existing .env ✓"
fi

# ── 3. Start Postgres + NATS + Vault ─────────────────────────────────
info "Starting PostgreSQL + NATS + Vault..."

if docker ps --format '{{.Names}}' | grep -q '^gradient-db$'; then
  info "  PostgreSQL already running ✓"
else
  docker compose up -d postgres 2>/dev/null || docker-compose up -d postgres 2>/dev/null
  info "  Waiting for PostgreSQL to be ready..."
  for i in $(seq 1 30); do
    if docker exec gradient-db pg_isready -U gradient >/dev/null 2>&1; then
      break
    fi
    sleep 1
  done
  if ! docker exec gradient-db pg_isready -U gradient >/dev/null 2>&1; then
    fail "PostgreSQL failed to start after 30s"
  fi
  info "  PostgreSQL ready ✓"
fi

if docker ps --format '{{.Names}}' | grep -q '^gradient-nats$'; then
  info "  NATS already running ✓"
else
  docker compose up -d nats 2>/dev/null || docker-compose up -d nats 2>/dev/null
  info "  Waiting for NATS to be ready..."
  for i in $(seq 1 15); do
    if curl -sf http://localhost:8222/healthz >/dev/null 2>&1; then
      break
    fi
    sleep 1
  done
  if curl -sf http://localhost:8222/healthz >/dev/null 2>&1; then
    info "  NATS (JetStream) ready ✓"
  else
    warn "  NATS failed to start — Live Context Mesh will use local mode"
  fi
fi

if docker ps --format '{{.Names}}' | grep -q '^gradient-vault$'; then
  info "  Vault already running ✓"
else
  docker compose --profile secrets up -d vault 2>/dev/null || docker-compose --profile secrets up -d vault 2>/dev/null
  info "  Waiting for Vault to be ready..."
  for i in $(seq 1 15); do
    if curl -sf http://localhost:8200/v1/sys/health >/dev/null 2>&1; then
      break
    fi
    sleep 1
  done
  if curl -sf http://localhost:8200/v1/sys/health >/dev/null 2>&1; then
    # Mount KV v2 engine for Gradient secrets
    curl -sf -X POST http://localhost:8200/v1/sys/mounts/gradient \
      -H "X-Vault-Token: dev-token" \
      -H "Content-Type: application/json" \
      -d '{"type":"kv","options":{"version":"2"}}' 2>/dev/null || true
    info "  Vault (dev mode) ready — token: dev-token ✓"
  else
    warn "  Vault failed to start — secret sync will skip Vault"
  fi

  # Set Vault env vars if not already in .env
  if grep -q "^VAULT_ADDR=$" .env 2>/dev/null; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
      sed -i '' 's|^VAULT_ADDR=.*|VAULT_ADDR=http://localhost:8200|' .env
      sed -i '' 's|^VAULT_TOKEN=.*|VAULT_TOKEN=dev-token|' .env
    else
      sed -i 's|^VAULT_ADDR=.*|VAULT_ADDR=http://localhost:8200|' .env
      sed -i 's|^VAULT_TOKEN=.*|VAULT_TOKEN=dev-token|' .env
    fi
  fi
fi

# ── 4. Stripe setup (credits price, meter, webhook) ─────────────────
# Only runs if STRIPE_SECRET_KEY is set and the credits price is still TODO/empty.
# NOTE: We read vars with grep+cut instead of `source .env` because the SSH private key
# contains characters that break shell sourcing.
STRIPE_SECRET_KEY=$(grep "^STRIPE_SECRET_KEY=" .env 2>/dev/null | cut -d= -f2-)

if [ -n "$STRIPE_SECRET_KEY" ] && grep -q "TODO_CREATE_CREDITS_PRODUCT\|^STRIPE_PRICE_CREDITS_ID=$" .env 2>/dev/null; then
  info "Setting up Stripe credits meter and price..."

  # Helper: create billing meter + credits product + usage-based price.
  # The price is modeled as $3 / 1000 credits on a monthly meter.
  create_stripe_credits_price() {
    local product_name="$1" unit_amount="$2" meter_event="$3" meter_display="$4"

    # Step 1: Create Billing Meter
    local meter_response
    meter_response=$(curl -s -X POST https://api.stripe.com/v1/billing/meters \
      -u "$STRIPE_SECRET_KEY:" \
      -d "display_name=$meter_display" \
      -d "event_name=$meter_event" \
      -d "default_aggregation[formula]=sum")

    local meter_id
    meter_id=$(echo "$meter_response" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null)

    if [ -z "$meter_id" ]; then
      echo ""
      return
    fi

    # Step 2: Create Product
    local product_response
    product_response=$(curl -s -X POST https://api.stripe.com/v1/products \
      -u "$STRIPE_SECRET_KEY:" \
      -d "name=$product_name" \
      -d "metadata[app]=gradient" \
      -d "metadata[meter_event]=$meter_event")

    local product_id
    product_id=$(echo "$product_response" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null)

    if [ -z "$product_id" ]; then
      echo ""
      return
    fi

    # Step 3: Create Price linked to the meter
    local price_response
    price_response=$(curl -s -X POST https://api.stripe.com/v1/prices \
      -u "$STRIPE_SECRET_KEY:" \
      -d "product=$product_id" \
      -d "unit_amount=$unit_amount" \
      -d "currency=usd" \
      -d "recurring[interval]=month" \
      -d "recurring[usage_type]=metered" \
      -d "recurring[meter]=$meter_id" \
      -d "transform_quantity[divide_by]=1000" \
      -d "transform_quantity[round]=up" \
      -d "billing_scheme=per_unit")

    local price_id
    price_id=$(echo "$price_response" | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null)

    echo "$price_id"
  }

  CREDITS_PRICE=$(create_stripe_credits_price 'Gradient Credits' 300 'gradient_credits' 'Gradient Credits')

  if [ -n "$CREDITS_PRICE" ]; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
      sed -i '' "s|^STRIPE_PRICE_CREDITS_ID=.*|STRIPE_PRICE_CREDITS_ID=$CREDITS_PRICE|" .env
    else
      sed -i "s|^STRIPE_PRICE_CREDITS_ID=.*|STRIPE_PRICE_CREDITS_ID=$CREDITS_PRICE|" .env
    fi
    info "  Credits price: $CREDITS_PRICE ✓"
  else
    warn "  Failed to create Stripe credits product — check STRIPE_SECRET_KEY"
  fi

  # Webhook: For local dev, Stripe CLI handles this (can't create localhost webhooks via API).
  # Generate a local signing secret so the handler doesn't reject events.
  if grep -q "TODO_CREATE_WEBHOOK_ENDPOINT\|^STRIPE_WEBHOOK_SECRET=$" .env 2>/dev/null; then
    # Use `stripe listen` for local webhook forwarding. Generate a placeholder secret.
    LOCAL_WEBHOOK_SECRET="whsec_local_$(openssl rand -hex 16)"
    if [[ "$OSTYPE" == "darwin"* ]]; then
      sed -i '' "s|^STRIPE_WEBHOOK_SECRET=.*|STRIPE_WEBHOOK_SECRET=$LOCAL_WEBHOOK_SECRET|" .env
    else
      sed -i "s|^STRIPE_WEBHOOK_SECRET=.*|STRIPE_WEBHOOK_SECRET=$LOCAL_WEBHOOK_SECRET|" .env
    fi
    info "  Webhook: using local secret (for production, use Stripe Dashboard) ✓"
    info "  To test webhooks locally: stripe listen --forward-to localhost:6767/api/v1/webhooks/stripe"
  fi
else
  if [ -n "$STRIPE_SECRET_KEY" ]; then
    info "Stripe already configured ✓"
  else
    warn "No STRIPE_SECRET_KEY in .env — Stripe setup skipped"
  fi
fi

# ── 5. Clerk JWKS URL (auto-derive from secret key) ─────────────────
# Read vars with grep+cut (not `source`) — SSH private key breaks shell sourcing
CLERK_SK=$(grep "^CLERK_SECRET_KEY=" .env 2>/dev/null | cut -d= -f2-)
CLERK_JWKS_CURRENT=$(grep "^CLERK_JWKS_URL=" .env 2>/dev/null | cut -d= -f2-)

if [ -n "$CLERK_SK" ] && ! echo "$CLERK_JWKS_CURRENT" | grep -q "^http" 2>/dev/null; then
  info "Verifying Clerk JWKS access..."
  # Clerk Backend API /v1/jwks returns JWKS directly (no frontend URL needed)
  JWKS_VALID=$(curl -sf -H "Authorization: Bearer $CLERK_SK" \
    https://api.clerk.com/v1/jwks 2>/dev/null | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print('yes' if 'keys' in d and len(d['keys']) > 0 else 'no')
except:
    print('no')
" 2>/dev/null || echo "no")

  if [ "$JWKS_VALID" = "yes" ]; then
    # Use the Clerk Backend API JWKS endpoint directly
    JWKS_URL="https://api.clerk.com/v1/jwks"
    if [[ "$OSTYPE" == "darwin"* ]]; then
      sed -i '' "s|^CLERK_JWKS_URL=.*|CLERK_JWKS_URL=$JWKS_URL|" .env
    else
      sed -i "s|^CLERK_JWKS_URL=.*|CLERK_JWKS_URL=$JWKS_URL|" .env
    fi
    info "  JWKS: verified via Clerk Backend API ✓"
  else
    warn "  Could not verify Clerk JWKS — check CLERK_SECRET_KEY"
  fi
elif [ -n "$CLERK_SK" ]; then
  info "Clerk JWKS URL already configured ✓"
else
  info "No CLERK_SECRET_KEY — running in dev mode (no JWT verification)"
fi

# Derive Clerk publishable key from secret key (pk_test_ = base64 of frontend API domain)
CLERK_PK_CURRENT=$(grep "^CLERK_PUBLISHABLE_KEY=" .env 2>/dev/null | cut -d= -f2-)
if [ -n "$CLERK_SK" ] && [ -z "$CLERK_PK_CURRENT" ]; then
  info "Deriving Clerk publishable key..."
  # The Clerk publishable key is pk_test_<base64(frontend_api_domain)> or pk_live_<base64(...)>
  # We can get the frontend API from the instance config
  INSTANCE_INFO=$(curl -sf -H "Authorization: Bearer $CLERK_SK" \
    https://api.clerk.com/v1/instance 2>/dev/null || echo "")
  if [ -n "$INSTANCE_INFO" ]; then
    # Extract the environment type to determine pk_test_ vs pk_live_
    ENV_TYPE=$(echo "$INSTANCE_INFO" | python3 -c "import sys,json; print(json.load(sys.stdin).get('environment_type','development'))" 2>/dev/null || echo "development")
    # The frontend API domain can be derived from the secret key pattern or found in Clerk Dashboard
    # For now, try to extract from Clerk's well-known endpoint
    PK_PREFIX="pk_test_"
    if [ "$ENV_TYPE" = "production" ]; then
      PK_PREFIX="pk_live_"
    fi
    # Check if the key is in the format sk_test_xxx → the Clerk publishable key should already be known
    # Users should set this from the Clerk Dashboard
    info "  Set CLERK_PUBLISHABLE_KEY from Clerk Dashboard → API Keys → Publishable key"
  fi
fi

# Auto-generate JWT_SECRET if not set
JWT_SECRET_CURRENT=$(grep "^JWT_SECRET=" .env 2>/dev/null | cut -d= -f2-)
if [ -z "$JWT_SECRET_CURRENT" ]; then
  info "Generating JWT signing secret..."
  JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s|^JWT_SECRET=.*|JWT_SECRET=$JWT_SECRET|" .env
  else
    sed -i "s|^JWT_SECRET=.*|JWT_SECRET=$JWT_SECRET|" .env
  fi
  info "  JWT_SECRET generated ✓"
else
  info "JWT_SECRET already configured ✓"
fi

# ── 6. Hetzner SSH key (auto-generate + upload) ─────────────────────
HETZNER_API_TOKEN=$(grep "^HETZNER_API_TOKEN=" .env 2>/dev/null | cut -d= -f2-)

if [ -n "$HETZNER_API_TOKEN" ] && (grep -q "TODO_UPLOAD_SSH_KEY\|^HETZNER_SSH_KEY_IDS=$" .env 2>/dev/null); then
  info "Setting up Hetzner SSH key..."
  SSH_KEY_PATH="$HOME/.ssh/gradient-key"

  # Generate key if it doesn't exist
  if [ ! -f "$SSH_KEY_PATH" ]; then
    ssh-keygen -t ed25519 -f "$SSH_KEY_PATH" -N "" -C "gradient-dev" >/dev/null 2>&1
    info "  Generated SSH key: $SSH_KEY_PATH ✓"
  else
    info "  SSH key already exists: $SSH_KEY_PATH ✓"
  fi

  PUBLIC_KEY=$(cat "${SSH_KEY_PATH}.pub")

  # Check if key already exists in Hetzner by public key match
  EXISTING_ID=$(curl -s -H "Authorization: Bearer $HETZNER_API_TOKEN" \
    https://api.hetzner.cloud/v1/ssh_keys 2>/dev/null | \
    python3 -c "
import sys, json, os
try:
    data = json.load(sys.stdin)
    pub = open(os.path.expanduser('${SSH_KEY_PATH}.pub')).read().strip()
    for k in data.get('ssh_keys', []):
        if k.get('public_key','').strip() == pub:
            print(k['id'])
            break
except: pass
" 2>/dev/null || true)

  if [ -n "$EXISTING_ID" ]; then
    HETZNER_KEY_ID="$EXISTING_ID"
    info "  SSH key already uploaded to Hetzner (ID: $HETZNER_KEY_ID) ✓"
  else
    # Upload to Hetzner
    UPLOAD_RESPONSE=$(curl -s -X POST \
      -H "Authorization: Bearer $HETZNER_API_TOKEN" \
      -H "Content-Type: application/json" \
      -d "{\"name\":\"gradient-dev-$(hostname -s)\",\"public_key\":\"$PUBLIC_KEY\"}" \
      https://api.hetzner.cloud/v1/ssh_keys 2>/dev/null)

    HETZNER_KEY_ID=$(echo "$UPLOAD_RESPONSE" | grep -o '"id":[0-9]*' | head -1 | cut -d: -f2)

    if [ -n "$HETZNER_KEY_ID" ]; then
      info "  Uploaded SSH key to Hetzner (ID: $HETZNER_KEY_ID) ✓"
    else
      warn "  Failed to upload SSH key to Hetzner — check API token"
      HETZNER_KEY_ID=""
    fi
  fi

  if [ -n "$HETZNER_KEY_ID" ]; then
    # Write key ID to .env
    if [[ "$OSTYPE" == "darwin"* ]]; then
      sed -i '' "s|^HETZNER_SSH_KEY_IDS=.*|HETZNER_SSH_KEY_IDS=$HETZNER_KEY_ID|" .env
    else
      sed -i "s|^HETZNER_SSH_KEY_IDS=.*|HETZNER_SSH_KEY_IDS=$HETZNER_KEY_ID|" .env
    fi

    # Write single-line private key to .env (use python3 — sed can't handle \n in replacement)
    python3 -c "
import os
key = open(os.path.expanduser('$SSH_KEY_PATH')).read().strip()
single = key.replace(chr(10), r'\n')
with open('.env') as f:
    content = f.read()
import re
content = re.sub(r'^HETZNER_SSH_PRIVATE_KEY=.*$', f'HETZNER_SSH_PRIVATE_KEY={single}', content, flags=re.MULTILINE)
with open('.env', 'w') as f:
    f.write(content)
"
    info "  Wrote HETZNER_SSH_KEY_IDS=$HETZNER_KEY_ID to .env ✓"
  fi
else
  if [ -n "$HETZNER_API_TOKEN" ]; then
    info "Hetzner SSH key already configured ✓"
  else
    warn "No HETZNER_API_TOKEN — Hetzner SSH setup skipped"
  fi
fi

# ── 7. Install Go dependencies ────────────────────────────────────────
info "Installing Go dependencies..."
go mod download
info "  Dependencies installed ✓"

# ── 8. Build all binaries ────────────────────────────────────────────
info "Building binaries..."
go build -o bin/gradient-api cmd/api/main.go
go build -o bin/gc cmd/cli/main.go
go build -o bin/gradient-mcp cmd/mcp/main.go
go build -o bin/gradient-agent cmd/agent/main.go
info "  bin/gradient-api   ✓"
info "  bin/gc (CLI)       ✓"
info "  bin/gradient-mcp   ✓"
info "  bin/gradient-agent ✓"

# ── 9. Run tests ─────────────────────────────────────────────────────
info "Running tests..."
if go test ./... -count=1 -short 2>&1 | tail -1 | grep -q "^ok"; then
  PASS_COUNT=$(go test ./... -count=1 -short 2>&1 | grep -c "^ok" || true)
  info "  All tests passed ($PASS_COUNT packages) ✓"
else
  warn "  Some tests may have issues — check with: go test ./... -v"
fi

# ── 10. Run migrations ───────────────────────────────────────────────
info "Running database migrations..."
# Export only the vars the API needs to start (avoid `source .env` — SSH key breaks it)
export PORT=$(grep "^PORT=" .env | cut -d= -f2-)
export ENV=$(grep "^ENV=" .env | cut -d= -f2-)
export DATABASE_URL=$(grep "^DATABASE_URL=" .env | cut -d= -f2-)
export CLERK_SECRET_KEY=$(grep "^CLERK_SECRET_KEY=" .env | cut -d= -f2-)
export CLERK_JWKS_URL=$(grep "^CLERK_JWKS_URL=" .env | cut -d= -f2-)
export NATS_URL=$(grep "^NATS_URL=" .env | cut -d= -f2-)
export HETZNER_API_TOKEN=$(grep "^HETZNER_API_TOKEN=" .env | cut -d= -f2-)
export HETZNER_LOCATION=$(grep "^HETZNER_LOCATION=" .env | cut -d= -f2-)
export LOG_LEVEL=$(grep "^LOG_LEVEL=" .env | cut -d= -f2-)

# Kill any stale process on the API port
API_PORT="${PORT:-6767}"
if lsof -ti :"$API_PORT" >/dev/null 2>&1; then
  info "  Killing stale process on port $API_PORT..."
  lsof -ti :"$API_PORT" | xargs kill -9 2>/dev/null || true
  sleep 1
fi

bin/gradient-api &
API_PID=$!
sleep 3

if curl -sf http://localhost:${PORT:-6767}/api/v1/health >/dev/null 2>&1; then
  info "  Migrations applied, API healthy ✓"
else
  warn "  API started but health check pending"
fi

kill $API_PID 2>/dev/null || true
wait $API_PID 2>/dev/null || true

# ── Done! ─────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}  ┌──────────────────────────────────────┐${NC}"
echo -e "${GREEN}  │         Setup Complete! 🚀            │${NC}"
echo -e "${GREEN}  └──────────────────────────────────────┘${NC}"
echo ""
echo "  Start the API server:"
echo "    make run-api"
echo ""
echo "  Or run directly:"
echo "    ./bin/gradient-api"
echo ""
echo "  CLI usage:"
echo "    ./bin/gc env list"
echo "    ./bin/gc env create --name my-env --region fsn1"
echo "    ./bin/gc env health <env-id>"
echo "    ./bin/gc env ssh <env-id>"
echo "    ./bin/gc env logs <env-id>"
echo "    ./bin/gc env exec <env-id> -- python train.py"
echo ""
echo "  MCP server (for AI agents):"
echo "    ./bin/gradient-mcp"
echo ""
echo "  Hetzner infra setup (production):"
echo "    ./scripts/setup-hetzner-infra.sh"
echo "    ./scripts/build-hetzner-snapshot.sh"
echo ""
echo "  API health check:"
echo "    curl http://localhost:6767/api/v1/health"
echo ""
