server_name: gradient-nats

listen: 0.0.0.0:4222

jetstream {
    store_dir: /data/jetstream
    max_mem_store: 128MB
    max_file_store: 512MB
}

authorization {
    token: "40c63c9fd443c8f20d1ae632005c3d69"
}

http_port: 8222

max_connections: 1000
max_payload: 1MB
write_deadline: 10s
